### ISSUE TITLE
Home page redesign

### ISSUE THREAD

**Issue by Bailey-Pearson** [maksymko/CodeU-Spring-2018#72]
Visually redesign the home page to make it more simplistic and remove the list of things to do that currently don't always apply to everyone

**Comment by maksymko** [comment]
This needs to be split into multiple issues. Right now it's unclear what exactly do you intend to do.

**Comment by Bailey-Pearson** [comment]
Current WIP design

![image](https://user-images.githubusercontent.com/29077792/39549060-82182d44-4e2a-11e8-95c7-4657fe1ec1e0.png)
